package com.rdfs.message;

public enum MessageType {
	GET_NEW_DATANODE_LOCATIONS_REQUEST, 
	GET_DATANODE_LOCATIONS_REQUEST,
	GET_BLOCK_LOCATIONS_REQUEST,
	READ_BLOCK_REQUEST,
	WRITE_BLOCK_REQUEST,
	DELETE_BLOCK_REQUEST;
}