package com.rdfs;

public class Constants {
	public static final long DEFAULT_BLOCK_SIZE;
	public static final String DEFAULT_NAME_NODE_ADDRESS;
	public static final int DEFAULT_NAME_NODE_PORT;
	public static final int DEFAULT_DATA_NODE_PORT;
	public static final int DEFAULT_HEARTBEAT_PORT;
	public static final int DEFAULT_HEARTBEAT_THREAD_SLEEP_DURATION;
	public static final int DEFAULT_HEARTBEAT_THRESHOLD;
	public static final int DEFAULT_REPLICATION_FACTOR;

	static {
		DEFAULT_BLOCK_SIZE = (long) 128e6;
		DEFAULT_NAME_NODE_ADDRESS = "0.0.0.0";
		DEFAULT_NAME_NODE_PORT = 3620;
		DEFAULT_DATA_NODE_PORT = 3530;
		DEFAULT_HEARTBEAT_PORT = 3630;
		DEFAULT_HEARTBEAT_THRESHOLD = 7000;
		DEFAULT_HEARTBEAT_THREAD_SLEEP_DURATION = 1000;
		DEFAULT_REPLICATION_FACTOR = 2;
	}
}
